// Angular build information, automatically generated by `generate-build-infos` script
export const buildInfos = {
  hash: '<git_commit_hash>',
  user: '<git_user>',
  jenkinsBuildNumber: 12345,
  timestamp: '<build_timestamp>'
};
